spring.application.name=fuelmeup-backend

spring.datasource.url=jdbc:postgresql://localhost:5433/fuelmeup
spring.datasource.username=postgres
spring.datasource.password=Archit1604$
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}
jwt.expiration=36000000