spring.application.name=fuelmeup-backend


spring.datasource.url=${DATA_SOURCE_URL}
spring.datasource.username=${DATA_SOURCE_USERNAME}
spring.datasource.password=${DATA_SOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}
jwt.expiration=36000000

razorpay.key-id=rzp_test_TB5LwGNUZ8ZzHK
razorpay.key-secret=5nApAcABp6YQeXXfXUE7y9YH

razorpay.webhook-secret=K3$bsW45@sd